project_id = "mwvtnvhaxaymmklipffc"

[functions.place-order]
verify_jwt = false

[functions.steadfast-courier]
verify_jwt = false

[functions.courier-history]
verify_jwt = false

[functions.facebook-capi]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
